name: run main.py

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch: {}

jobs:
  aggregate:
    name: Aggregate Smartraveller Destinations and Advisories
    runs-on: ubuntu-latest
    permissions:
      # Give GITHUB_TOKEN write permission to commit and push changes
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run aggregation script
        run: python smartraveller/aggregate.py

      - name: Commit aggregated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Smartraveller data"